# Generated by Django 4.0.2 on 2022-02-19 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainerapp', '0004_remove_trainer_user_trainerlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='trainers',
            field=models.ManyToManyField(to='trainerapp.TrainerList'),
        ),
    ]
