# Generated by Django 4.0.2 on 2022-02-20 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainerapp', '0005_trainer_trainers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='trainers',
        ),
        migrations.DeleteModel(
            name='TrainerList',
        ),
    ]
